### ISSUE TITLE
Brazalian (Português Brasil) <pt-br.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/SafetyWall#18]
# Localization - ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

## To Be Done by :octocat: contributor

* Some helpful reading
  * [Readme on localization][lclztn]
  * [Quickstart guide to localization][qs]
  * these should help guide you
  * both are in markdown {text}
  * if you are feeling very helpful, kindly translate these as well. ;P
* GameData (done by contributor)
  * [ ] add Localization\<pt-br.cfg> 🗃️
* Translation
  * [ ] ![Português Brasil][BR] Brazilian Portuguese (Português Brasil) <pt-br.cfg>

1. Fork this repo
2. Create a branch name it 'translations' or localizations (suggestions)
3. goto `GameData/.../Localization/`
4. copy <en-us.cfg>
5. rename to <pt-br.cfg>
6. open the file and translate everything to the right of `#??? = `
7. change the `en-us` to `pt-br`
8. please include an attribution to you in the localization file, something like:
  * `// Translated by: [GitHubUserName](https://github.com/GitHubUserName)`
  * alternatively if you want another name from the KSP forums...
9. when done, PR it and you could reference this issue
10. After it has been merged by me, you may delete your fork.

have fun and thank you! :octocat: 🎃

## GitHub

* Completed:
  * [x] assign
    * [x] zer0Kerbal
    * [x] Repo Localization Project
    * [x] Label: type: localization
    * [x] Label: help-wanted
    * [x] hacktoberfest
    * [x] good-first-issue
    * [x] contributions-welcome
    * [x] beginner-friendly
    * [x] Milestone: Localization - Master

### below done by @zer0Kerbal

* Update
  * Documentation
    * [ ] [readme.md] 🔢
    * [ ] [release.md] 🧾
  * docs/
    * [ ] docs/[localization.md]
  * Update Social Media
  * [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
  * [x] CurseForge
  * [x] Reddit
  * [x] Twitter @zer0Kerbal
  * [x] Forum
  * [x] Patreon
  * [x] SpaceDock
  * [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/BR.png "Brazil"

this file: © All Rights Reserved by zer0Kerbal
@lisias

**Comment by ClaraSantosmf** [comment]
Can i help you? I'm brazilian.

**Comment by zer0Kerbal** [comment]
> Can i help you? I'm brazilian.

Yes, kindly follow the instructions above and translate the file en-us.cfg into a new file pt-br.cfg.

**Comment by ClaraSantosmf** [comment]
Please, I have a question. When you mention 'SafetyWall', do you envision a safety fence like [this](https://img.directindustry.com/pt/images_di/photo-m2/126165-15608793.jpg) or a protective wall like [this](https://i0.wp.com/gestaodesegurancaprivada.com.br/wp-content/uploads/muro-de-protecao.jpg?fit=720%2C402&ssl=1)? There are different translation for these structures. In case none of them apply, could you provide an image as an example?

**Comment by zer0Kerbal** [comment]
this is a safety barrier around a space port to protect the public from concrete flying at the speed of sound as a rocket takes off, along with keeping people out so they don't get fried by said rocket's firey plume of death. 😁

![image](https://user-images.githubusercontent.com/39887717/236991913-67e4948f-a211-4f9a-a20b-f863ba67e544.png)
